import Head from "next/head";
import { useEffect } from "react";
import IndexPage from "../Components/IndexPage";

import styles from "../styles/Home.module.css";

// Importing icons
import { AiOutlineInfoCircle } from "react-icons/ai";
import { SiNounproject } from "react-icons/si";
import { AiOutlineBulb } from "react-icons/ai";
import { MdOutlineTimeline } from "react-icons/md";

export default function Home(props) {
  const sideNav = [
    {
      title: "Intro",
      tag: "#intro",
      icon: <AiOutlineInfoCircle />,
    },
    {
      title: "Projects",
      tag: "#",
      icon: <SiNounproject />,
    },
    {
      title: "Skills",
      tag: "#",
      icon: <AiOutlineBulb />,
    },
    {
      title: "Timeline",
      tag: "#",
      icon: <MdOutlineTimeline />,
    },
  ];

  useEffect(() => {
    props.setSideNavData(sideNav);
  }, []);

  return (
    <>
      <Head>
        <title>Aniruddha Gawali | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <main className={styles.main}>
        <IndexPage />
      </main>
    </>
  );
}
